[build]
  functions = "functions"

[build.environment]
  GO_VERSION = "1.19.6"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
